// Code generated by Kitex v0.3.1. DO NOT EDIT.

package search

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	searchapi "searchengine3090ti/kitex_gen/SearchApi"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Query(ctx context.Context, req *searchapi.QueryRequest, callOptions ...callopt.Option) (r *searchapi.QueryResponse, err error)
	Add(ctx context.Context, req *searchapi.AddRequest, callOptions ...callopt.Option) (r *searchapi.AddResponse, err error)
	RelatedQuery(ctx context.Context, req *searchapi.RelatedQueryRequest, callOptions ...callopt.Option) (r *searchapi.RelatedQueryResponse, err error)
	FindID(ctx context.Context, req *searchapi.FindIDRequest, callOptions ...callopt.Option) (r *searchapi.FindIDResponse, err error)
	QueryIDNumber(ctx context.Context, req *searchapi.QueryIDNumberRequest, callOptions ...callopt.Option) (r *searchapi.QueryIDNumberResponse, err error)
	Imgquery(ctx context.Context, req *searchapi.ImgQueryRequest, callOptions ...callopt.Option) (r *searchapi.ImgQueryResponse, err error)
	Wd2imgquery(ctx context.Context, req *searchapi.Wd2imgQueryRequest, callOptions ...callopt.Option) (r *searchapi.Wd2imgQueryResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSearchClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSearchClient struct {
	*kClient
}

func (p *kSearchClient) Query(ctx context.Context, req *searchapi.QueryRequest, callOptions ...callopt.Option) (r *searchapi.QueryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Query(ctx, req)
}

func (p *kSearchClient) Add(ctx context.Context, req *searchapi.AddRequest, callOptions ...callopt.Option) (r *searchapi.AddResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Add(ctx, req)
}

func (p *kSearchClient) RelatedQuery(ctx context.Context, req *searchapi.RelatedQueryRequest, callOptions ...callopt.Option) (r *searchapi.RelatedQueryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RelatedQuery(ctx, req)
}

func (p *kSearchClient) FindID(ctx context.Context, req *searchapi.FindIDRequest, callOptions ...callopt.Option) (r *searchapi.FindIDResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FindID(ctx, req)
}

func (p *kSearchClient) QueryIDNumber(ctx context.Context, req *searchapi.QueryIDNumberRequest, callOptions ...callopt.Option) (r *searchapi.QueryIDNumberResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryIDNumber(ctx, req)
}

func (p *kSearchClient) Imgquery(ctx context.Context, req *searchapi.ImgQueryRequest, callOptions ...callopt.Option) (r *searchapi.ImgQueryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Imgquery(ctx, req)
}

func (p *kSearchClient) Wd2imgquery(ctx context.Context, req *searchapi.Wd2imgQueryRequest, callOptions ...callopt.Option) (r *searchapi.Wd2imgQueryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Wd2imgquery(ctx, req)
}
