// Code generated by Kitex v0.3.1. DO NOT EDIT.

package search

import (
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	searchapi "search/kitex_gen/SearchApi"
)

func serviceInfo() *kitex.ServiceInfo {
	return searchServiceInfo
}

var searchServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Search"
	handlerType := (*searchapi.Search)(nil)
	methods := map[string]kitex.MethodInfo{
		"query": kitex.NewMethodInfo(queryHandler, newSearchQueryArgs, newSearchQueryResult, false),
		"add":   kitex.NewMethodInfo(addHandler, newSearchAddArgs, newSearchAddResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "searchapi",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.3.1",
		Extra:           extra,
	}
	return svcInfo
}

func queryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*searchapi.SearchQueryArgs)
	realResult := result.(*searchapi.SearchQueryResult)
	success, err := handler.(searchapi.Search).Query(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSearchQueryArgs() interface{} {
	return searchapi.NewSearchQueryArgs()
}

func newSearchQueryResult() interface{} {
	return searchapi.NewSearchQueryResult()
}

func addHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*searchapi.SearchAddArgs)
	realResult := result.(*searchapi.SearchAddResult)
	success, err := handler.(searchapi.Search).Add(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSearchAddArgs() interface{} {
	return searchapi.NewSearchAddArgs()
}

func newSearchAddResult() interface{} {
	return searchapi.NewSearchAddResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Query(ctx context.Context, req *searchapi.QueryRequest) (r *searchapi.QueryResponse, err error) {
	var _args searchapi.SearchQueryArgs
	_args.Req = req
	var _result searchapi.SearchQueryResult
	if err = p.c.Call(ctx, "query", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Add(ctx context.Context, req *searchapi.AddRequest) (r *searchapi.AddResponse, err error) {
	var _args searchapi.SearchAddArgs
	_args.Req = req
	var _result searchapi.SearchAddResult
	if err = p.c.Call(ctx, "add", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
